version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: ubereats-redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - ubereats-network

  ubereats-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubereats-mcp-server
    ports:
      - "5000:5000"
      - "9090:9090"  # Metrics port
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - N8N_BASE_URL=${N8N_BASE_URL:-http://localhost:5678}
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - ubereats-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  redis-data:
    driver: local

networks:
  ubereats-network:
    driver: bridge